# Generated by Django 5.1.4 on 2024-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AddField(
            model_name='artefact',
            name='user_generated_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artefact',
            name='artefact_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='condition',
            field=models.CharField(blank=True, default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artefact',
            name='context',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artefact',
            name='description',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artefact',
            name='material',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artefact',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
