# Generated by Django 5.1.4 on 2025-01-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='artefact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AddField(
            model_name='site',
            name='admins',
            field=models.ManyToManyField(to='archiving.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='sites',
            field=models.ManyToManyField(blank=True, to='archiving.site'),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiving.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiving.user')),
            ],
        ),
    ]
