# Generated by Django 5.1.4 on 2025-01-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0004_remove_user_is_staff_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='join_as_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
