# Generated by Django 5.1.4 on 2025-01-04 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0005_joinrequest_join_as_admin_joinrequest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sites',
        ),
        migrations.AddField(
            model_name='site',
            name='members',
            field=models.ManyToManyField(related_name='member_sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='admins',
            field=models.ManyToManyField(related_name='admin_sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
