# Generated by Django 5.1.4 on 2025-01-05 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0006_remove_user_sites_site_members_alter_site_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
